---
version: "3.7"
services:
  mfer-node:
   build: .
   ports: 
    - "8545:8545"
    - "10545:10545"
   restart: unless-stopped
   command: 'mfer-node --upstream https://cloudflare-eth.com'
   #cloudflare eth is a freely accessible ethereum node, can be removed to be replaced by localhost:8545 as default or can be replaced to any other node url like Infura/Alchemy etc.
